/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Library */

#ifndef _Included_Library
#define _Included_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Library
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Library_hello
  (JNIEnv *, jobject);

/*
 * Class:     Library
 * Method:    someRandoms
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Library_someRandoms
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
