/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utility */

#ifndef _Included_Utility
#define _Included_Utility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utility
 * Method:    hello
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Utility_hello
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
