/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utility */

#ifndef _Included_Utility
#define _Included_Utility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utility
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Utility_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
